### ISSUE TITLE
bug: Docker build failing for Mac M1

### ISSUE THREAD

**Issue by varunjain15** [starkware-libs/papyrus#1436]
# Bug Report

**Papyrus version:**

6ae90e27

**Current behavior:**

building docker file for MacM1 is returning error
```
executor failed running [/bin/sh -c rustup target add x86_64-unknown-linux-musl &&     CARGO_INCREMENTAL=0 cargo build  --target x86_64-unknown-linux-musl --release --package papyrus_node &&     CARGO_INCREMENTAL=0 cargo build   --target x86_64-unknown-linux-musl --release --package papyrus_load_test]: exit code: 137
```

**Expected behavior:**

Docker image should get created

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

1. we need to use this specific commit version because we are on a custom app chain on starknet and we are getting issues related to `0x` errors while trying with latest version / release tag
2. we are unable to build docker image for Mac M1 platform however able to run the node locally

**Comment by Cevedale** [comment]
The reported issue involves building a Docker image for the Papyrus version 6ae90e2 on a Mac M1 platform, resulting in an exit code 137. To resolve this, it is suggested to check and adjust resource allocations in Docker settings, ensure correct configurations for Rustup and Cargo targeting the x86_64-unknown-linux-musl platform, review the Dockerfile for proper architecture specifications, and consider using Docker Buildx for multi-platform support. Additionally, investigating commit-specific changes and seeking community support for the Papyrus project may provide insights into resolving the issue.
