### ISSUE TITLE
bug: RPC is not responding anything

### ISSUE THREAD

**Issue by Okm165** [starkware-libs/papyrus#1859]
# Bug Report

**Papyrus version:**

Latest Release
sha256:0f29a084003b9d05ba28b44f6ac9ada10c3604b10bc55d36f04e72b56d379071

**Current behavior:**

RPC is not responding
```
curl: (52) Empty reply from server
```

**Expected behavior:**

RPC should return some response other then empty

**Steps to reproduce:**

```
docker run --rm --name papyrus\
  -p 8080-8081:8080-8081 \
  -v /<local-host-data-path>:/app/data \
  --memory 1g
  ghcr.io/starkware-libs/papyrus:latest \
  --base_layer.node_url <ethereum_node_url> \
  --user "$(id -u):$(id -g)"
```

```
curl --location 'localhost:8080/rpc/v0_4_0' --header 'Content-Type: application/json'\
 --data '\{"jsonrpc":"2.0","id":0,"method":"starknet_getBlockTransactionCount", "params": [{"block_number": 100000}] }'
 curl: (52) Empty reply from server
```

**Comment by eitanm-starkware** [comment]
Thanks for posting. Attached PR fixes it 
[https://github.com/starkware-libs/papyrus/pull/1881](https://github.com/starkware-libs/papyrus/pull/1881)
