### ISSUE TITLE
feat: Hardware and bandwidth requirements

### ISSUE THREAD

**Issue by randomishwalk** [starkware-libs/papyrus#452]
# Feature Request

Would love the StarkNet community and Starkware team to provide more color on what type of hardware / bandwidth needs are needed to run this full node effectively, particularly under various scenarios of onchain activity. Do I need a bare metal data center? Generic Kubernetes cluster/public managed cloud services? Custom hardware? My normal everyday laptop? etc

**Describe Alternatives**

One "alternative" may just be to continuously collect and sample full node runners on StarkNet what their exact setup is, costs associated etc. This would be extremely helpful data to inform who can / can't afford or have the know-how on how to run these nodes. Particularly, if this needs to run on non-standard, non-consumer grade hardware (which it seems like it might if there's a lot of onchain activity).

**Related Code**

N/A

**Additional Context**

ethereum.org and mainnet EL/CL teams have decent documentation around what running various node setups require. I believe the Rocket Pool / Dappnode (solo-staker) community has generated good documentation for L1 mainnet and have some degree of consensus on agreed-upon, efficient, somewhat cost-effective setups. Perhaps we look to those communities for assistance and inspiration.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by randomishwalk** [comment]
Here is, as one example, what the Rocket Pool community has pulled together (alongside many other resources) to assist home stakers / professional RP pool operators get setup. It also serves as an important signal to prospective network participants how they can participate by giving them a good sense for the financial & operational burdens of running critical protocol infrastructure: https://docs.rocketpool.net/guides/node/vps/providers.html#provider-comparison-placeholders

**Comment by randomishwalk** [comment]
Why don't I start an Airtable so that community members like yourself can submit tech specs that other folks can look at for guidance? Would you be interested in contributing to that?

**Comment by randomishwalk** [comment]
Entry form here: https://airtable.com/shr3q6rDBT4n9FHCY

View-only table of responses: https://airtable.com/shrS72kzkoTBxNS0G

Please DM me if you'd like to collaborate on managing this (should be fairly self-service right now though, fine handling solo myself for now)

**Comment by milvinae** [comment]
Nice work

Can you update the input fields to allow alphanumeric? I can't enter the CPU as it only allows numbers.

**Comment by randomishwalk** [comment]
Ok should be updated! Same links as above
