### ISSUE TITLE
Adding a user agent

### ISSUE THREAD

**Issue by EvyatarO** [starkware-libs/papyrus#497]
### Objective
Add a user agent that includes the Papyrus version (currently hard-coded 'pre-release') and the OS as part of the HTTP requests.

**Comment by Kelvyne** [comment]
Hey, I would be interested in contributing.
Can you please elaborate about which HTTP requests you are talking about please ?

**Comment by abdelhamidbakhta** [comment]
> 

Assigned it to you

**Comment by EvyatarO** [comment]
> 

The starknet_client resquests (see [request](https://github.com/starkware-libs/papyrus/blob/9d87c606a331269b173f3d517424fc51b7f1713c/crates/starknet_client/src/lib.rs#L221) function)

**Comment by Kelvyne** [comment]
Hey, I won't be able to work on this atm

**Comment by ptisserand** [comment]
Hi, I'm interested to work on this.

**Comment by EvyatarO** [comment]
Assigned it to you

**Comment by ptisserand** [comment]
Any recommendation how I can retrieve OS information ?

**Comment by dan-starkware** [comment]
Consider using a crate such as [os_info](https://docs.rs/os_info/3.6.0/os_info/index.html).

**Comment by ptisserand** [comment]
Here is the aggent I received when running a local netcat + `config.yaml` modified to use my localhost:
```
$ netcat -l -p 5555
GET /feeder_gateway/get_block HTTP/1.1
accept: */*
user-agent: papyrus/pre-release (Arch Linux)
host: localhost:5555
```

Does it seems fine?

**Comment by dan-starkware** [comment]
Yes, consider adding some more info to the system information (distribution, version, architecture, etc.)

**Comment by ptisserand** [comment]
Version and architecture provided by `os_info` have been added.
```
GET /feeder_gateway/get_block HTTP/1.1
accept: */*
user-agent: papyrus/pre-release (Arch Linux; Rolling Release; 64-bit)
host: localhost:5555
```

**Comment by ptisserand** [comment]
I think we should close this one.
